import { Category, Product } from "./types";

export const categories: Category[] = [
  {
    slug: "school-furniture",
    name: "School Furniture",
    shortName: "Furniture",
    tagline: "Built for better classrooms.",
    description:
      "Desks, chairs and storage engineered for daily institutional use — sourced for schools that plan to keep their furniture for decades, not semesters.",
    accent: "wood",
  },
  {
    slug: "educational-materials",
    name: "Educational Materials",
    shortName: "Learning",
    tagline: "Learning, made tangible.",
    description:
      "Montessori-aligned boards, counting sets and manipulatives shaped from solid wood, designed to put real materials back into early learning.",
    accent: "sage",
  },
  {
    slug: "kitchen",
    name: "Kitchen",
    shortName: "Kitchen",
    tagline: "Replace plastic with something made to last.",
    description:
      "Boards, utensils and everyday storage in oiled hardwood — a quieter, longer-lasting alternative to the plastic drawer.",
    accent: "wood",
  },
  {
    slug: "toys",
    name: "Toys",
    shortName: "Toys",
    tagline: "Play naturally. Learn endlessly.",
    description:
      "Rounded, finished-by-hand toys for infants and toddlers, built to survive years of play and the occasional sibling.",
    accent: "sage",
  },
];

const r = (
  id: string,
  name: string,
  rating: number,
  title: string,
  comment: string,
  date: string
) => ({ id, name, rating, title, comment, date });

export const products: Product[] = [
  // ---------------- SCHOOL FURNITURE ----------------
  {
    id: "p1",
    slug: "solid-oak-student-desk",
    name: "Solid Oak Student Desk",
    category: "school-furniture",
    art: "desk",
    tagline: "The desk your classroom won't need to replace.",
    description:
      "A single-seat desk built on a mortise-and-tenon frame with a solid oak top, sized for years of note-taking, projects and everyday classroom wear. Understorage keeps bags and books off the aisle.",
    price: 18500,
    currency: "PKR",
    rating: 4.8,
    reviewCount: 34,
    purchaseType: "quote",
    bulkPricing: true,
    badges: ["Made to Order"],
    material: "Solid oak, birch ply understorage",
    dimensions: "60cm × 50cm × 74cm (W × D × H)",
    finish: "Low-VOC matte sealant",
    care: "Wipe with a dry or lightly damp cloth. Avoid standing water.",
    inStock: true,
    reviews: [
      r("r1", "Amina R.", 5, "Still holding up after two years", "We ordered forty of these for our primary wing and they've taken a beating well. No wobble, no chipped edges.", "2026-03-11"),
      r("r2", "Head of Facilities, Riverbend School", 5, "Exactly what institutional furniture should be", "The quote process was straightforward and delivery was staged across two weeks to match our renovation schedule.", "2026-01-22"),
    ],
  },
  {
    id: "p2",
    slug: "stacking-classroom-chair",
    name: "Stacking Classroom Chair",
    category: "school-furniture",
    art: "chair",
    tagline: "Lightweight enough to stack, sturdy enough to trust.",
    description:
      "A steam-bent beechwood chair designed for fast room turnover — stacks five high for end-of-day cleaning without scuffing the finish.",
    price: 8900,
    currency: "PKR",
    rating: 4.7,
    reviewCount: 51,
    purchaseType: "cart",
    bulkPricing: true,
    badges: ["Bestseller"],
    material: "Steam-bent beechwood",
    dimensions: "40cm × 42cm × 78cm (W × D × H)",
    finish: "Satin water-based lacquer",
    care: "Wipe clean. Felt pads included for hard floors.",
    inStock: true,
    reviews: [
      r("r3", "Bilal K.", 5, "Cleaner does this in half the time now", "Stacking five at a time instead of two has genuinely changed our closing routine.", "2026-04-02"),
      r("r4", "Sana M.", 4, "Great chair, wish it came in more sizes", "Perfect for grades 4 and up. Ordering a smaller run for the junior wing separately.", "2026-02-14"),
    ],
  },
  {
    id: "p3",
    slug: "kindergarten-activity-table",
    name: "Kindergarten Activity Table",
    category: "school-furniture",
    art: "table",
    tagline: "Rounded edges, seats six, built for glue and glitter.",
    description:
      "A low, rounded-corner activity table sized for early years classrooms, finished to resist spills and stand up to daily art projects.",
    price: 26500,
    currency: "PKR",
    rating: 4.9,
    reviewCount: 19,
    purchaseType: "quote",
    bulkPricing: true,
    badges: ["Made to Order"],
    material: "Solid beech, rounded laminate top",
    dimensions: "120cm × 90cm × 48cm (W × D × H)",
    finish: "Spill-resistant sealed top",
    care: "Wipe immediately after messy activities.",
    inStock: true,
    reviews: [
      r("r5", "Founder, Little Pines Montessori", 5, "The rounded corners were non-negotiable for us", "Grain & Grid was the only supplier willing to customise the corner radius to our safety spec.", "2026-05-19"),
    ],
  },
  {
    id: "p4",
    slug: "reading-corner-bench",
    name: "Reading Corner Bench",
    category: "school-furniture",
    art: "bench",
    tagline: "A quiet seat for the library corner.",
    description:
      "A low bench with a gently curved seat, sized to fit a reading nook or hallway alcove without dominating the room.",
    price: 15200,
    currency: "PKR",
    rating: 4.6,
    reviewCount: 12,
    purchaseType: "cart",
    material: "Solid ash",
    dimensions: "110cm × 35cm × 42cm (W × D × H)",
    finish: "Hand-rubbed oil finish",
    care: "Re-oil lightly every 12 months.",
    inStock: true,
    reviews: [
      r("r6", "Faryal T.", 5, "Became the most fought-over seat in the library", "Simple, sturdy, and the curve is genuinely comfortable for a wooden bench.", "2026-03-28"),
    ],
  },
  {
    id: "p5",
    slug: "classroom-bookshelf-unit",
    name: "Classroom Bookshelf Unit",
    category: "school-furniture",
    art: "bookshelf",
    tagline: "Forward-facing storage that keeps covers visible.",
    description:
      "A low, child-height bookshelf with both flat and forward-facing shelving, so younger readers can choose books by their covers.",
    price: 22800,
    currency: "PKR",
    rating: 4.8,
    reviewCount: 15,
    purchaseType: "quote",
    bulkPricing: true,
    material: "Birch plywood, solid edging",
    dimensions: "100cm × 30cm × 90cm (W × D × H)",
    finish: "Low-VOC matte sealant",
    care: "Dust with a dry cloth.",
    inStock: true,
    reviews: [
      r("r7", "Librarian, Oakridge School", 5, "Circulation went up", "Putting picture books face-out made a bigger difference than we expected.", "2026-02-08"),
    ],
  },

  // ---------------- EDUCATIONAL MATERIALS ----------------
  {
    id: "p6",
    slug: "natural-oak-alphabet-board",
    name: "Natural Oak Alphabet Board",
    category: "educational-materials",
    art: "alphabet-board",
    tagline: "Letters you can hold before you can write them.",
    description:
      "Twenty-six laser-cut, hand-sanded oak letters set into a matching tray, designed for tracing, sequencing and early phonics work.",
    price: 3400,
    currency: "PKR",
    rating: 4.9,
    reviewCount: 128,
    purchaseType: "cart",
    badges: ["Bestseller"],
    material: "Solid oak",
    dimensions: "42cm × 30cm × 2cm",
    finish: "Child-safe, non-toxic oil finish",
    care: "Wipe with a dry cloth; avoid soaking.",
    inStock: true,
    reviews: [
      r("r8", "Sarah H.", 5, "Beautiful craftsmanship", "The finish is excellent and it feels far more premium than the price suggests.", "2026-04-15"),
      r("r9", "Hina A.", 5, "My daughter's favourite thing in the house", "She lines the letters up every morning before school. Worth every rupee.", "2026-03-02"),
      r("r10", "Zara I.", 4, "Lovely, just wish it shipped with a bag", "The board itself is excellent — I'd just like a pouch to keep loose letters together.", "2026-01-27"),
    ],
  },
  {
    id: "p7",
    slug: "wooden-abacus",
    name: "Classic Wooden Abacus",
    category: "educational-materials",
    art: "abacus",
    tagline: "The oldest counting tool, still the best one.",
    description:
      "A ten-row abacus with smooth beech beads on a solid frame, sized for small hands and built to survive a full school year on a classroom shelf.",
    price: 2600,
    currency: "PKR",
    rating: 4.7,
    reviewCount: 63,
    purchaseType: "cart",
    material: "Beech frame, hardwood beads",
    dimensions: "30cm × 22cm",
    finish: "Natural wax finish",
    care: "Wipe clean, keep away from direct heat.",
    inStock: true,
    reviews: [
      r("r11", "Junaid S.", 5, "Beads move smoothly, no snagging", "Bought two — one for home, one stayed in my son's school bag.", "2026-02-19"),
    ],
  },
  {
    id: "p8",
    slug: "montessori-shape-sorter",
    name: "Montessori Shape Sorter",
    category: "educational-materials",
    art: "shape-sorter",
    tagline: "Nine shapes, one lesson in problem-solving.",
    description:
      "A weighted base with nine geometric cut-outs and matching solid-wood shapes, sized for toddler grip and early spatial reasoning.",
    price: 2900,
    currency: "PKR",
    rating: 4.8,
    reviewCount: 47,
    purchaseType: "cart",
    ageGroup: "1–3 years",
    material: "Solid pine, non-toxic paint",
    dimensions: "24cm × 24cm × 6cm",
    finish: "Water-based, child-safe paint",
    care: "Wipe with a damp cloth.",
    inStock: true,
    reviews: [
      r("r12", "Mehwish D.", 5, "Held her attention longer than any plastic toy", "The weight of the pieces seems to matter — she concentrates so much harder with this than with plastic versions.", "2026-04-06"),
    ],
  },
  {
    id: "p9",
    slug: "counting-sorting-tray-set",
    name: "Counting & Sorting Tray Set",
    category: "educational-materials",
    art: "counting-tray",
    tagline: "A tray for every stage of early maths.",
    description:
      "Three stacking trays with 100 loose counting pieces, used for one-to-one correspondence, grouping and simple addition exercises.",
    price: 4200,
    currency: "PKR",
    rating: 4.6,
    reviewCount: 28,
    purchaseType: "cart",
    bulkPricing: true,
    material: "Solid beech",
    dimensions: "3 trays, 20cm × 15cm each",
    finish: "Natural wax finish",
    care: "Wipe clean.",
    inStock: true,
    reviews: [
      r("r13", "Maths Coordinator, Elm Grove School", 5, "Ordered a set for every table group", "Simple, durable, and the trays stack neatly into our storage cupboard between lessons.", "2026-01-30"),
    ],
  },
  {
    id: "p10",
    slug: "fraction-geometry-board",
    name: "Fraction & Geometry Board",
    category: "educational-materials",
    art: "geometry-board",
    tagline: "Fractions you can pick up and rearrange.",
    description:
      "A circular board with removable fraction segments and geometric inserts, built for hands-on work with halves, thirds and quarters.",
    price: 3800,
    currency: "PKR",
    rating: 4.7,
    reviewCount: 22,
    purchaseType: "cart",
    material: "Birch plywood, solid edging",
    dimensions: "28cm diameter",
    finish: "Low-VOC matte sealant",
    care: "Wipe with a dry cloth.",
    inStock: true,
    reviews: [
      r("r14", "Owais F.", 5, "Finally a fractions tool that isn't a worksheet", "My son understood thirds in about ten minutes with this.", "2026-03-17"),
    ],
  },

  // ---------------- KITCHEN ----------------
  {
    id: "p11",
    slug: "solid-walnut-cutting-board",
    name: "Solid Walnut Cutting Board",
    category: "kitchen",
    art: "cutting-board",
    tagline: "One board, long enough to outlast the plastic drawer.",
    description:
      "An end-grain walnut board that's gentle on knife edges and dense enough to resist warping — finished with food-safe oil, not lacquer.",
    price: 5200,
    currency: "PKR",
    rating: 4.9,
    reviewCount: 96,
    purchaseType: "cart",
    badges: ["Bestseller"],
    material: "End-grain walnut",
    dimensions: "40cm × 28cm × 3cm",
    finish: "Food-safe mineral oil and beeswax",
    care: "Hand wash and dry immediately. Re-oil monthly.",
    inStock: true,
    reviews: [
      r("r15", "Kiran W.", 5, "Threw out every plastic board I owned", "Heavier than I expected, in a good way — doesn't slide on the counter.", "2026-04-11"),
      r("r16", "Danish P.", 5, "Gift-worthy", "Bought one for myself and two as wedding gifts. All three recipients asked where it was from.", "2026-02-25"),
    ],
  },
  {
    id: "p12",
    slug: "everyday-utensil-set",
    name: "Everyday Utensil Set",
    category: "kitchen",
    art: "utensils",
    tagline: "Five tools, no plastic, no scratched pans.",
    description:
      "A spoon, spatula, slotted turner, fork and tasting spoon, carved from a single dense hardwood and finished smooth enough for daily use on non-stick cookware.",
    price: 3100,
    currency: "PKR",
    rating: 4.8,
    reviewCount: 54,
    purchaseType: "cart",
    material: "Solid acacia",
    dimensions: "5-piece set, 28–32cm each",
    finish: "Food-safe oil finish",
    care: "Hand wash, dry upright.",
    inStock: true,
    reviews: [
      r("r17", "Nida Q.", 5, "Better balance than my old metal set", "Sits comfortably in the hand and hasn't scratched my pans once.", "2026-03-06"),
    ],
  },
  {
    id: "p13",
    slug: "nesting-serving-trays",
    name: "Nesting Serving Trays",
    category: "kitchen",
    art: "tray",
    tagline: "Three trays, one shelf's worth of space.",
    description:
      "A set of three nesting serving trays with cut handles, sized for everything from breakfast in bed to a full dinner spread.",
    price: 4600,
    currency: "PKR",
    rating: 4.7,
    reviewCount: 31,
    purchaseType: "cart",
    material: "Solid mango wood",
    dimensions: "Small 25cm, Medium 32cm, Large 40cm",
    finish: "Food-safe oil finish",
    care: "Wipe clean, avoid soaking.",
    inStock: true,
    reviews: [
      r("r18", "Ayesha L.", 5, "Prettier than anything I've seen in stores here", "Use the large one as a centrepiece even when I'm not serving anything.", "2026-01-19"),
    ],
  },
  {
    id: "p14",
    slug: "airtight-storage-jar-trio",
    name: "Airtight Storage Jar Trio",
    category: "kitchen",
    art: "jar",
    tagline: "Glass jars, wood lids, no plastic seal.",
    description:
      "Three glass canisters with turned hardwood lids and a silicone gasket, sized for flour, rice and everyday dry goods.",
    price: 3900,
    currency: "PKR",
    rating: 4.6,
    reviewCount: 40,
    purchaseType: "cart",
    material: "Glass body, acacia lid",
    dimensions: "1L, 1.5L, 2L",
    finish: "Food-safe oil finish on lids",
    care: "Hand wash lids, dishwasher-safe jars.",
    inStock: true,
    reviews: [
      r("r19", "Tania B.", 4, "Great look, one lid was a slightly loose fit", "Support replaced it quickly when I flagged it. Otherwise very happy.", "2026-02-11"),
    ],
  },

  // ---------------- TOYS ----------------
  {
    id: "p15",
    slug: "heirloom-rocking-horse",
    name: "Heirloom Rocking Horse",
    category: "toys",
    art: "rocking-horse",
    tagline: "Built to be handed down, not outgrown quickly.",
    description:
      "A hand-sanded rocking horse with a low centre of gravity and rounded rockers, sized for toddlers just steady enough to climb on alone.",
    price: 9800,
    currency: "PKR",
    rating: 4.9,
    reviewCount: 41,
    purchaseType: "cart",
    ageGroup: "18 months – 4 years",
    badges: ["Bestseller"],
    material: "Solid beech",
    dimensions: "70cm × 25cm × 55cm",
    finish: "Child-safe, non-toxic oil finish",
    care: "Wipe clean. Check joints periodically.",
    inStock: true,
    reviews: [
      r("r20", "Farah N.", 5, "This is the toy that made me stop buying plastic", "Solid, quiet, no batteries, and it actually looks nice left out in the living room.", "2026-04-20"),
      r("r21", "Imran C.", 5, "My daughter's first, will pass to her cousin next", "Built like it's meant to survive more than one child.", "2026-03-09"),
    ],
  },
  {
    id: "p16",
    slug: "stacking-rings",
    name: "Rainbow Stacking Rings",
    category: "toys",
    art: "stacking-rings",
    tagline: "The first puzzle: biggest to smallest.",
    description:
      "Seven graduated rings on a rounded post, sized for grasping hands and an early lesson in order and balance.",
    price: 1800,
    currency: "PKR",
    rating: 4.8,
    reviewCount: 72,
    purchaseType: "cart",
    ageGroup: "6 months – 2 years",
    material: "Solid beech, non-toxic paint",
    dimensions: "16cm base, 18cm tall",
    finish: "Water-based, child-safe paint",
    care: "Wipe clean.",
    inStock: true,
    reviews: [
      r("r22", "Rabia G.", 5, "Chunky enough for tiny hands", "Withstood being chewed on for months without the paint chipping.", "2026-02-27"),
    ],
  },
  {
    id: "p17",
    slug: "push-and-pull-walker",
    name: "Push & Pull Walker",
    category: "toys",
    art: "push-toy",
    tagline: "First steps, steadied by solid wood.",
    description:
      "A weighted push walker with a fixed handle height and rounded wheels, built to stay stable under a new walker's full weight.",
    price: 5400,
    currency: "PKR",
    rating: 4.7,
    reviewCount: 33,
    purchaseType: "cart",
    ageGroup: "9 – 18 months",
    material: "Solid rubberwood",
    dimensions: "38cm × 30cm × 46cm",
    finish: "Child-safe, non-toxic oil finish",
    care: "Wipe clean, tighten wheel bolts periodically.",
    inStock: true,
    reviews: [
      r("r23", "Saad Z.", 5, "Steadier than the plastic ones we tried first", "It doesn't shoot forward the way lightweight walkers do — much less falling.", "2026-01-14"),
    ],
  },
  {
    id: "p18",
    slug: "balancing-blocks-set",
    name: "Balancing Blocks Set",
    category: "toys",
    art: "blocks",
    tagline: "Twenty-four shapes, endless towers.",
    description:
      "A 24-piece set of arches, cylinders and blocks in a mix of natural and lightly stained finishes, for building, balancing and knocking back down.",
    price: 3200,
    currency: "PKR",
    rating: 4.8,
    reviewCount: 58,
    purchaseType: "cart",
    ageGroup: "2 – 6 years",
    badges: ["New"],
    material: "Solid pine, natural and stained finishes",
    dimensions: "24-piece set, storage crate included",
    finish: "Child-safe, non-toxic oil and stain",
    care: "Wipe clean.",
    inStock: true,
    reviews: [
      r("r24", "Wajiha S.", 5, "Better quality than sets twice the price", "The crate alone makes tidy-up time so much easier.", "2026-04-01"),
    ],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getCategory(slug: string) {
  return categories.find((c) => c.slug === slug);
}

export function getRelatedProducts(product: Product, count = 4) {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, count);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.badges?.includes("Bestseller"));
}
